/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.studying.rpc.thrift.stub.service;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;

public class TestThriftService {

  public interface Iface {

    /**
     * value 中存放两个字符串拼接之后的字符串
     * 
     * @param srcStr1
     * @param srcStr2
     */
    public com.studying.rpc.thrift.stub.bean.ResultStr getStr(String srcStr1, String srcStr2) throws org.apache.thrift.TException;

    public com.studying.rpc.thrift.stub.bean.ResultInt getInt(int val) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void getStr(String srcStr1, String srcStr2, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.getStr_call> resultHandler) throws org.apache.thrift.TException;

    public void getInt(int val, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.getInt_call> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public com.studying.rpc.thrift.stub.bean.ResultStr getStr(String srcStr1, String srcStr2) throws org.apache.thrift.TException
    {
      send_getStr(srcStr1, srcStr2);
      return recv_getStr();
    }

    public void send_getStr(String srcStr1, String srcStr2) throws org.apache.thrift.TException
    {
      getStr_args args = new getStr_args();
      args.setSrcStr1(srcStr1);
      args.setSrcStr2(srcStr2);
      sendBase("getStr", args);
    }

    public com.studying.rpc.thrift.stub.bean.ResultStr recv_getStr() throws org.apache.thrift.TException
    {
      getStr_result result = new getStr_result();
      receiveBase(result, "getStr");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "getStr failed: unknown result");
    }

    public com.studying.rpc.thrift.stub.bean.ResultInt getInt(int val) throws org.apache.thrift.TException
    {
      send_getInt(val);
      return recv_getInt();
    }

    public void send_getInt(int val) throws org.apache.thrift.TException
    {
      getInt_args args = new getInt_args();
      args.setVal(val);
      sendBase("getInt", args);
    }

    public com.studying.rpc.thrift.stub.bean.ResultInt recv_getInt() throws org.apache.thrift.TException
    {
      getInt_result result = new getInt_result();
      receiveBase(result, "getInt");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "getInt failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void getStr(String srcStr1, String srcStr2, org.apache.thrift.async.AsyncMethodCallback<getStr_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      getStr_call method_call = new getStr_call(srcStr1, srcStr2, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getStr_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String srcStr1;
      private String srcStr2;
      public getStr_call(String srcStr1, String srcStr2, org.apache.thrift.async.AsyncMethodCallback<getStr_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.srcStr1 = srcStr1;
        this.srcStr2 = srcStr2;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("getStr", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getStr_args args = new getStr_args();
        args.setSrcStr1(srcStr1);
        args.setSrcStr2(srcStr2);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public com.studying.rpc.thrift.stub.bean.ResultStr getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getStr();
      }
    }

    public void getInt(int val, org.apache.thrift.async.AsyncMethodCallback<getInt_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      getInt_call method_call = new getInt_call(val, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getInt_call extends org.apache.thrift.async.TAsyncMethodCall {
      private int val;
      public getInt_call(int val, org.apache.thrift.async.AsyncMethodCallback<getInt_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.val = val;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("getInt", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getInt_args args = new getInt_args();
        args.setVal(val);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public com.studying.rpc.thrift.stub.bean.ResultInt getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getInt();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("getStr", new getStr());
      processMap.put("getInt", new getInt());
      return processMap;
    }

    private static class getStr<I extends Iface> extends org.apache.thrift.ProcessFunction<I, getStr_args> {
      public getStr() {
        super("getStr");
      }

      protected getStr_args getEmptyArgsInstance() {
        return new getStr_args();
      }

      protected getStr_result getResult(I iface, getStr_args args) throws org.apache.thrift.TException {
        getStr_result result = new getStr_result();
        result.success = iface.getStr(args.srcStr1, args.srcStr2);
        return result;
      }
    }

    private static class getInt<I extends Iface> extends org.apache.thrift.ProcessFunction<I, getInt_args> {
      public getInt() {
        super("getInt");
      }

      protected getInt_args getEmptyArgsInstance() {
        return new getInt_args();
      }

      protected getInt_result getResult(I iface, getInt_args args) throws org.apache.thrift.TException {
        getInt_result result = new getInt_result();
        result.success = iface.getInt(args.val);
        return result;
      }
    }

  }

  public static class getStr_args implements org.apache.thrift.TBase<getStr_args, getStr_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getStr_args");

    private static final org.apache.thrift.protocol.TField SRC_STR1_FIELD_DESC = new org.apache.thrift.protocol.TField("srcStr1", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField SRC_STR2_FIELD_DESC = new org.apache.thrift.protocol.TField("srcStr2", org.apache.thrift.protocol.TType.STRING, (short)2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getStr_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getStr_argsTupleSchemeFactory());
    }

    public String srcStr1; // required
    public String srcStr2; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SRC_STR1((short)1, "srcStr1"),
      SRC_STR2((short)2, "srcStr2");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // SRC_STR1
            return SRC_STR1;
          case 2: // SRC_STR2
            return SRC_STR2;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SRC_STR1, new org.apache.thrift.meta_data.FieldMetaData("srcStr1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.SRC_STR2, new org.apache.thrift.meta_data.FieldMetaData("srcStr2", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getStr_args.class, metaDataMap);
    }

    public getStr_args() {
    }

    public getStr_args(
      String srcStr1,
      String srcStr2)
    {
      this();
      this.srcStr1 = srcStr1;
      this.srcStr2 = srcStr2;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getStr_args(getStr_args other) {
      if (other.isSetSrcStr1()) {
        this.srcStr1 = other.srcStr1;
      }
      if (other.isSetSrcStr2()) {
        this.srcStr2 = other.srcStr2;
      }
    }

    public getStr_args deepCopy() {
      return new getStr_args(this);
    }

    @Override
    public void clear() {
      this.srcStr1 = null;
      this.srcStr2 = null;
    }

    public String getSrcStr1() {
      return this.srcStr1;
    }

    public getStr_args setSrcStr1(String srcStr1) {
      this.srcStr1 = srcStr1;
      return this;
    }

    public void unsetSrcStr1() {
      this.srcStr1 = null;
    }

    /** Returns true if field srcStr1 is set (has been assigned a value) and false otherwise */
    public boolean isSetSrcStr1() {
      return this.srcStr1 != null;
    }

    public void setSrcStr1IsSet(boolean value) {
      if (!value) {
        this.srcStr1 = null;
      }
    }

    public String getSrcStr2() {
      return this.srcStr2;
    }

    public getStr_args setSrcStr2(String srcStr2) {
      this.srcStr2 = srcStr2;
      return this;
    }

    public void unsetSrcStr2() {
      this.srcStr2 = null;
    }

    /** Returns true if field srcStr2 is set (has been assigned a value) and false otherwise */
    public boolean isSetSrcStr2() {
      return this.srcStr2 != null;
    }

    public void setSrcStr2IsSet(boolean value) {
      if (!value) {
        this.srcStr2 = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SRC_STR1:
        if (value == null) {
          unsetSrcStr1();
        } else {
          setSrcStr1((String)value);
        }
        break;

      case SRC_STR2:
        if (value == null) {
          unsetSrcStr2();
        } else {
          setSrcStr2((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SRC_STR1:
        return getSrcStr1();

      case SRC_STR2:
        return getSrcStr2();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SRC_STR1:
        return isSetSrcStr1();
      case SRC_STR2:
        return isSetSrcStr2();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getStr_args)
        return this.equals((getStr_args)that);
      return false;
    }

    public boolean equals(getStr_args that) {
      if (that == null)
        return false;

      boolean this_present_srcStr1 = true && this.isSetSrcStr1();
      boolean that_present_srcStr1 = true && that.isSetSrcStr1();
      if (this_present_srcStr1 || that_present_srcStr1) {
        if (!(this_present_srcStr1 && that_present_srcStr1))
          return false;
        if (!this.srcStr1.equals(that.srcStr1))
          return false;
      }

      boolean this_present_srcStr2 = true && this.isSetSrcStr2();
      boolean that_present_srcStr2 = true && that.isSetSrcStr2();
      if (this_present_srcStr2 || that_present_srcStr2) {
        if (!(this_present_srcStr2 && that_present_srcStr2))
          return false;
        if (!this.srcStr2.equals(that.srcStr2))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getStr_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getStr_args typedOther = (getStr_args)other;

      lastComparison = Boolean.valueOf(isSetSrcStr1()).compareTo(typedOther.isSetSrcStr1());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSrcStr1()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.srcStr1, typedOther.srcStr1);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetSrcStr2()).compareTo(typedOther.isSetSrcStr2());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSrcStr2()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.srcStr2, typedOther.srcStr2);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getStr_args(");
      boolean first = true;

      sb.append("srcStr1:");
      if (this.srcStr1 == null) {
        sb.append("null");
      } else {
        sb.append(this.srcStr1);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("srcStr2:");
      if (this.srcStr2 == null) {
        sb.append("null");
      } else {
        sb.append(this.srcStr2);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getStr_argsStandardSchemeFactory implements SchemeFactory {
      public getStr_argsStandardScheme getScheme() {
        return new getStr_argsStandardScheme();
      }
    }

    private static class getStr_argsStandardScheme extends StandardScheme<getStr_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getStr_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // SRC_STR1
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.srcStr1 = iprot.readString();
                struct.setSrcStr1IsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // SRC_STR2
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.srcStr2 = iprot.readString();
                struct.setSrcStr2IsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getStr_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.srcStr1 != null) {
          oprot.writeFieldBegin(SRC_STR1_FIELD_DESC);
          oprot.writeString(struct.srcStr1);
          oprot.writeFieldEnd();
        }
        if (struct.srcStr2 != null) {
          oprot.writeFieldBegin(SRC_STR2_FIELD_DESC);
          oprot.writeString(struct.srcStr2);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getStr_argsTupleSchemeFactory implements SchemeFactory {
      public getStr_argsTupleScheme getScheme() {
        return new getStr_argsTupleScheme();
      }
    }

    private static class getStr_argsTupleScheme extends TupleScheme<getStr_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getStr_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSrcStr1()) {
          optionals.set(0);
        }
        if (struct.isSetSrcStr2()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetSrcStr1()) {
          oprot.writeString(struct.srcStr1);
        }
        if (struct.isSetSrcStr2()) {
          oprot.writeString(struct.srcStr2);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getStr_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.srcStr1 = iprot.readString();
          struct.setSrcStr1IsSet(true);
        }
        if (incoming.get(1)) {
          struct.srcStr2 = iprot.readString();
          struct.setSrcStr2IsSet(true);
        }
      }
    }

  }

  public static class getStr_result implements org.apache.thrift.TBase<getStr_result, getStr_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getStr_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getStr_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getStr_resultTupleSchemeFactory());
    }

    public com.studying.rpc.thrift.stub.bean.ResultStr success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.studying.rpc.thrift.stub.bean.ResultStr.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getStr_result.class, metaDataMap);
    }

    public getStr_result() {
    }

    public getStr_result(
      com.studying.rpc.thrift.stub.bean.ResultStr success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getStr_result(getStr_result other) {
      if (other.isSetSuccess()) {
        this.success = new com.studying.rpc.thrift.stub.bean.ResultStr(other.success);
      }
    }

    public getStr_result deepCopy() {
      return new getStr_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public com.studying.rpc.thrift.stub.bean.ResultStr getSuccess() {
      return this.success;
    }

    public getStr_result setSuccess(com.studying.rpc.thrift.stub.bean.ResultStr success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((com.studying.rpc.thrift.stub.bean.ResultStr)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getStr_result)
        return this.equals((getStr_result)that);
      return false;
    }

    public boolean equals(getStr_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getStr_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getStr_result typedOther = (getStr_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getStr_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getStr_resultStandardSchemeFactory implements SchemeFactory {
      public getStr_resultStandardScheme getScheme() {
        return new getStr_resultStandardScheme();
      }
    }

    private static class getStr_resultStandardScheme extends StandardScheme<getStr_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getStr_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new com.studying.rpc.thrift.stub.bean.ResultStr();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getStr_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getStr_resultTupleSchemeFactory implements SchemeFactory {
      public getStr_resultTupleScheme getScheme() {
        return new getStr_resultTupleScheme();
      }
    }

    private static class getStr_resultTupleScheme extends TupleScheme<getStr_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getStr_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getStr_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new com.studying.rpc.thrift.stub.bean.ResultStr();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

  public static class getInt_args implements org.apache.thrift.TBase<getInt_args, getInt_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getInt_args");

    private static final org.apache.thrift.protocol.TField VAL_FIELD_DESC = new org.apache.thrift.protocol.TField("val", org.apache.thrift.protocol.TType.I32, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getInt_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getInt_argsTupleSchemeFactory());
    }

    public int val; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      VAL((short)1, "val");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // VAL
            return VAL;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __VAL_ISSET_ID = 0;
    private BitSet __isset_bit_vector = new BitSet(1);
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.VAL, new org.apache.thrift.meta_data.FieldMetaData("val", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getInt_args.class, metaDataMap);
    }

    public getInt_args() {
    }

    public getInt_args(
      int val)
    {
      this();
      this.val = val;
      setValIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getInt_args(getInt_args other) {
      __isset_bit_vector.clear();
      __isset_bit_vector.or(other.__isset_bit_vector);
      this.val = other.val;
    }

    public getInt_args deepCopy() {
      return new getInt_args(this);
    }

    @Override
    public void clear() {
      setValIsSet(false);
      this.val = 0;
    }

    public int getVal() {
      return this.val;
    }

    public getInt_args setVal(int val) {
      this.val = val;
      setValIsSet(true);
      return this;
    }

    public void unsetVal() {
      __isset_bit_vector.clear(__VAL_ISSET_ID);
    }

    /** Returns true if field val is set (has been assigned a value) and false otherwise */
    public boolean isSetVal() {
      return __isset_bit_vector.get(__VAL_ISSET_ID);
    }

    public void setValIsSet(boolean value) {
      __isset_bit_vector.set(__VAL_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case VAL:
        if (value == null) {
          unsetVal();
        } else {
          setVal((Integer)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case VAL:
        return Integer.valueOf(getVal());

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case VAL:
        return isSetVal();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getInt_args)
        return this.equals((getInt_args)that);
      return false;
    }

    public boolean equals(getInt_args that) {
      if (that == null)
        return false;

      boolean this_present_val = true;
      boolean that_present_val = true;
      if (this_present_val || that_present_val) {
        if (!(this_present_val && that_present_val))
          return false;
        if (this.val != that.val)
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getInt_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getInt_args typedOther = (getInt_args)other;

      lastComparison = Boolean.valueOf(isSetVal()).compareTo(typedOther.isSetVal());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetVal()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.val, typedOther.val);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getInt_args(");
      boolean first = true;

      sb.append("val:");
      sb.append(this.val);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bit_vector = new BitSet(1);
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getInt_argsStandardSchemeFactory implements SchemeFactory {
      public getInt_argsStandardScheme getScheme() {
        return new getInt_argsStandardScheme();
      }
    }

    private static class getInt_argsStandardScheme extends StandardScheme<getInt_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getInt_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // VAL
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.val = iprot.readI32();
                struct.setValIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getInt_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        oprot.writeFieldBegin(VAL_FIELD_DESC);
        oprot.writeI32(struct.val);
        oprot.writeFieldEnd();
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getInt_argsTupleSchemeFactory implements SchemeFactory {
      public getInt_argsTupleScheme getScheme() {
        return new getInt_argsTupleScheme();
      }
    }

    private static class getInt_argsTupleScheme extends TupleScheme<getInt_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getInt_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetVal()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetVal()) {
          oprot.writeI32(struct.val);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getInt_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.val = iprot.readI32();
          struct.setValIsSet(true);
        }
      }
    }

  }

  public static class getInt_result implements org.apache.thrift.TBase<getInt_result, getInt_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getInt_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getInt_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getInt_resultTupleSchemeFactory());
    }

    public com.studying.rpc.thrift.stub.bean.ResultInt success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.studying.rpc.thrift.stub.bean.ResultInt.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getInt_result.class, metaDataMap);
    }

    public getInt_result() {
    }

    public getInt_result(
      com.studying.rpc.thrift.stub.bean.ResultInt success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getInt_result(getInt_result other) {
      if (other.isSetSuccess()) {
        this.success = new com.studying.rpc.thrift.stub.bean.ResultInt(other.success);
      }
    }

    public getInt_result deepCopy() {
      return new getInt_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public com.studying.rpc.thrift.stub.bean.ResultInt getSuccess() {
      return this.success;
    }

    public getInt_result setSuccess(com.studying.rpc.thrift.stub.bean.ResultInt success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((com.studying.rpc.thrift.stub.bean.ResultInt)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getInt_result)
        return this.equals((getInt_result)that);
      return false;
    }

    public boolean equals(getInt_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getInt_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getInt_result typedOther = (getInt_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getInt_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getInt_resultStandardSchemeFactory implements SchemeFactory {
      public getInt_resultStandardScheme getScheme() {
        return new getInt_resultStandardScheme();
      }
    }

    private static class getInt_resultStandardScheme extends StandardScheme<getInt_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getInt_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new com.studying.rpc.thrift.stub.bean.ResultInt();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getInt_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getInt_resultTupleSchemeFactory implements SchemeFactory {
      public getInt_resultTupleScheme getScheme() {
        return new getInt_resultTupleScheme();
      }
    }

    private static class getInt_resultTupleScheme extends TupleScheme<getInt_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getInt_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getInt_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new com.studying.rpc.thrift.stub.bean.ResultInt();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
